export { default as PlusOutline } from '@ant-design/icons/lib/outline/PlusOutline'
export { default as SettingOutline } from '@ant-design/icons/lib/outline/SettingOutline'
export { default as CheckOutline } from '@ant-design/icons/lib/outline/CheckOutline'
export { default as LoadingOutline } from '@ant-design/icons/lib/outline/LoadingOutline'
export { default as CloseCircleFill } from '@ant-design/icons/lib/fill/CloseCircleFill'
export { default as CheckCircleFill } from '@ant-design/icons/lib/fill/CheckCircleFill'